In [1]:
### OPEN CSV AND OUTPUT SAMPLE

import csv
import random
import pandas as pd

path = 'MBB_year_by_year.csv'

df = pd.read_csv(path)

In [2]:
### sample 10 rows
df.sample(10)

,Team,Year,GamesPlayed,Win,Loss,Tie,Win_Pct,WinForfeit,LossForfeit,OvertimeWin,OvertimeLoss,PointsScored,AVGPointsScored,PointsAllowed,AVGPointsAllowed,PointDiff,AVGPointDiff,SeasonType
2695,Dexter,2015.0,22,10,12,0,0.454545,0,0,0,0,1039.0,47.227273,1056.0,48.000000,-17.0,-0.772727,Overall
36406,Redford Thurston,2022.0,8,5,3,0,0.625000,0,0,0,0,488.0,61.000000,464.0,58.000000,24.0,3.000000,Away
35724,Muskegon Western Michigan Christian,2021.0,10,4,6,0,0.400000,0,0,0,0,464.0,46.400000,601.0,60.100000,-137.0,-13.700000,Away
15816,Waldron,2019.0,14,5,9,0,0.357143,0,0,0,0,677.0,48.357143,887.0,63.357143,-210.0,-15.000000,Regular Season
24042,Taylor Trillium Academy,2021.0,4,3,1,0,0.750000,0,0,0,0,258.0,64.500000,180.0,45.000000,78.0,19.500000,Playoff
61933,East Kentwood,2014.0,3,3,0,0,1.000000,0,0,0,0,204.0,68.000000,127.0,42.333333,77.0,25.666667,Blowout_Wins
59011,Vassar,2012.0,4,3,1,0,0.750000,0,0,0,0,226.0,56.500000,220.0,55.000000,6.0,1.500000,Close
56685,New Baltimore Anchor Bay,2020.0,1,0,1,0,0.000000,0,0,0,0,59.0,59.000000,62.0,62.000000,-3.0,-3.000000,Close
1147,Bronson,2013.0,20,1,19,0,0.050000,0,0,0,0,948.0,47.400000,1269.0,63.450000,-321.0,-16.050000,Overall
73337,Powers North Central,2020.0,2,0,2,0,0.000000,0,0,0,0,93.0,46.500000,155.0,77.500000,-62.0,-31.000000,Blowout_Loses